# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckIXetjdBsOAG2Anf4eLenksLBPsCpBV
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.express as px

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(page_title="Customer Segmentation", layout="wide")

st.title("🛍️ Retail Customer Segmentation Dashboard")
st.markdown("Analyze customer behavior and predict segments")

# -----------------------------
# LOAD DATA & MODEL
# -----------------------------
@st.cache_data
def load_data():
    return pd.read_csv("data/features.csv")

@st.cache_resource
def load_model():
    kmeans = joblib.load("model/kmeans.pkl")
    scaler = joblib.load("model/scaler.pkl")
    return kmeans, scaler

df = load_data()
kmeans, scaler = load_model()

# -----------------------------
# SEGMENT MAPPING
# -----------------------------
def map_segment(cluster):
    mapping = {
        0: "⚠️ At Risk",
        1: "🛍️ Regular",
        2: "💎 High Value",
        3: "🆕 New / Occasional",
        4: "⭐ Potential Loyal"
    }
    return mapping.get(cluster, "Unknown")

df["Segment"] = df["Cluster"].apply(map_segment)

# -----------------------------
# SIDEBAR INPUT
# -----------------------------
st.sidebar.header("🔍 Customer Input")

recency = st.sidebar.slider("Recency (days)", 0, 365, 50)
frequency = st.sidebar.slider("Frequency", 1, 50, 5)
monetary = st.sidebar.slider("Monetary Spend", 0, 20000, 1000)

# Derived features (approximation)
avg_order_value = monetary / frequency
customer_lifespan = recency + np.random.randint(10, 100)
days_since_first = recency + np.random.randint(20, 150)
avg_purchase_interval = max(1, recency // max(1, frequency))
purchase_consistency = np.random.uniform(1, 10)
purchase_diversity = np.random.uniform(1, 5)

# -----------------------------
# PREDICTION
# -----------------------------
if st.sidebar.button("Predict Segment"):

    input_data = np.array([[recency, frequency, monetary,
                            avg_order_value,
                            customer_lifespan,
                            days_since_first,
                            avg_purchase_interval,
                            purchase_consistency,
                            purchase_diversity]])

    input_scaled = scaler.transform(input_data)
    cluster = kmeans.predict(input_scaled)[0]
    segment = map_segment(cluster)

    st.sidebar.success(f"Segment: {segment}")

# -----------------------------
# MAIN LAYOUT
# -----------------------------

# Row 1
col1, col2 = st.columns(2)

# -----------------------------
# SEGMENT DISTRIBUTION
# -----------------------------
with col1:
    st.subheader("📊 Segment Distribution")

    fig = px.histogram(
        df,
        x="Segment",
        color="Segment",
        title="Customer Segment Distribution"
    )
    st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# FREQUENCY VS MONETARY
# -----------------------------
with col2:
    st.subheader("📈 Frequency vs Monetary")

    fig = px.scatter(
        df,
        x="Frequency",
        y="Monetary",
        color="Segment",
        hover_data=["Recency"],
        title="Customer Segmentation"
    )
    st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# RECENCY VS FREQUENCY
# -----------------------------
st.subheader("📉 Recency vs Frequency")

fig = px.scatter(
    df,
    x="Recency",
    y="Frequency",
    color="Segment",
    title="Customer Activity Analysis"
)

st.plotly_chart(fig, use_container_width=True)

# -----------------------------
# CUSTOMER PROFILE CARD
# -----------------------------
st.subheader("👤 Sample Customer Profile")

sample = df.sample(1).iloc[0]

col1, col2, col3 = st.columns(3)

col1.metric("Recency", int(sample["Recency"]))
col2.metric("Frequency", int(sample["Frequency"]))
col3.metric("Monetary", int(sample["Monetary"]))

st.markdown(f"**Segment:** {sample['Segment']}")

# -----------------------------
# BUSINESS INSIGHTS
# -----------------------------
st.subheader("💡 Business Insights")

st.markdown("""
### 💎 High Value Customers
- Offer loyalty rewards
- Exclusive deals
- Early access to products

### ⭐ Potential Loyal Customers
- Encourage repeat purchases
- Upsell premium products

### 🛍️ Regular Customers
- Improve engagement
- Offer bundle deals

### 🆕 New Customers
- Provide onboarding offers
- First-time discounts

### ⚠️ At Risk Customers
- Run reactivation campaigns
- Provide discounts and reminders
""")